In [3]:
import numpy as np

In [4]:
students = np.array(['Alice','Bob','Charlie','David','Eva'])

In [5]:
students

array(['Alice', 'Bob', 'Charlie', 'David', 'Eva'], dtype='<U7')

In [6]:
grades = np.array([[85, 90, 78], [88, 92, 35], [76, 30, 68], [91, 87, 95], [65, 70, 60]])

In [9]:
grades

array([[85, 90, 78],
       [88, 92, 85],
       [76, 80, 68],
       [91, 87, 95],
       [65, 70, 60]])

In [11]:
#Calculating average per student
avg_per_student = np.mean(grades,axis=1,dtype=int)
avg_per_student

array([84, 71, 58, 91, 65])

In [13]:
#Calculating average per subject
avg_per_subject = np.mean(grades,axis=0,dtype=int)
avg_per_subject                          

array([81, 73, 67])

In [15]:
for i in range(len(students)):
    print(students[i],":",avg_per_student[i])

Alice : 84
Bob : 71
Charlie : 58
David : 91
Eva : 65


In [17]:
print("\nAverage marks per subject (Math, Science, English):", avg_per_subject)
avg_per_subject


Average marks per subject (Math, Science, English): [81 73 67]


array([81, 73, 67])

In [19]:
class_avg = np.mean(grades)
print("\nOverall class average:", class_avg)


Overall class average: 74.0


In [21]:
def categorize_grades(avg_score):
    if avg_score >= 90:
        return 'A'
    elif avg_score >= 80:
        return 'B'
    elif avg_score >= 70:
        return 'C'
    elif avg_score >= 60:
        return 'D'
    else:
        return 'F'

grade_categories = np.array([categorize_grades(avg_per_student[i]) for i in range(len(students))])

# Printing grade categories for each student
for i in range(len(students)):
    print(students[i], ":", grade_categories[i])

Alice : B
Bob : C
Charlie : F
David : A
Eva : D


In [23]:
top_n_indices = np.argsort(avg_per_student)[-3:][::-1]
top_students = students[top_n_indices]

print("\nTop 3 students based on average grades:", top_students)


Top 3 students based on average grades: ['David' 'Alice' 'Bob']


In [25]:
pass_fail = np.where(grades >= 40, 'Pass', 'Fail')

# Printing pass/fail status for each student by subject
for i in range(len(students)):
    print(students[i], ":", pass_fail[i])

Alice : ['Pass' 'Pass' 'Pass']
Bob : ['Pass' 'Pass' 'Fail']
Charlie : ['Pass' 'Fail' 'Pass']
David : ['Pass' 'Pass' 'Pass']
Eva : ['Pass' 'Pass' 'Pass']
